FROM node

WORKDIR /app/frontend

COPY ./package.json /app/frontend
COPY ./yarn.lock /app/frontend
COPY ./tsconfig.json /app/frontend
COPY ./tsconfig.node.json /app/frontend

RUN yarn

COPY . .

EXPOSE 5173

CMD yarn dev
