CREATE DATABASE notesDB;

use notesDB;

CREATE TABLE notes(
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(300),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  important BOOLEAN NOT NULL DEFAULT 0
);
